### ISSUE TITLE
only-profile and whoami are evaluated as strings instead of booleans ?

### ISSUE THREAD

**Issue by awoimbee** [Moulick/configure-multiple-aws-roles#9]
Hi,
Just wanted to say that I had issues with `only-profile: false` and `only-profile: "false"` not working. In fact what worked for me is `only-profile: ''`!

I know there is something in the actions syntax about if conditions not needing `${{ }}` but it never worked for me. If wrapping the condition doesn't fix it, then we should try something like `if: ${{ input.only-profile == true }}`.

Sorry I don't have much time (nor a local [`act`](https://github.com/nektos/act) setup on podman) to make a better repport, thanks for distributing this action !

**Comment by Moulick** [comment]
@awoimbee Thanks for the report, I'll try to replicate!

**Comment by Moulick** [comment]
@awoimbee Fixed in the latest release. You were indeed correct, it is evaluated as a string, and single quoted string at that. It looks like GitHub actions only support string inputs for actions. It supports defining `type` of input only in workflows.
